<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Calculation" Id="{8e43417b-80ab-4210-84c1-a49010fa957e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Calculation EXTENDS TcBaseModuleRegistered
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Calculation">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>